### ISSUE TITLE
Replace Buttons with a Navbar in the Home Page 

### ISSUE THREAD

**Issue by dynamoh** [dynamoh/PathFinding-Visualizer#1]
![issue121](https://user-images.githubusercontent.com/48164297/96350777-f84f7480-10d4-11eb-8d21-e2fae7733cf4.jpeg)

**Comment by ryanc16** [comment]
Would you want a navbar to reach the other solver visualization pages? Needs odd to use a navbar for the buttons that interact with the solver visualization itself.

**Comment by ryanc16** [comment]
Would you want a navbar to reach the other solver visualization pages? Seems odd to use a navbar for the buttons that interact with the solver visualization itself.

**Comment by GrayJacketStudios** [comment]
Hey, solved this for you but you dont give permissions to push a new branch to the project
